version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=customer_db
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db:3306", "--timeout=90", "--", "gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - ./logs:/app/logs

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: customer_db
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -psecret"]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 30s

volumes:
  db_data: